### ISSUE TITLE
删除图片的时候没有回调事件吗

### ISSUE THREAD

**Issue by Kolentoo** [eJayYoung/vux-uploader-component#1]
就是点那个预览下面的垃圾桶的时候

**Comment by eJayYoung** [comment]
目前是没有加，因为预览的删除操作是直接删除缓存里的图片，所以没考虑在删除那里需要跟接口有交互

**Comment by eJayYoung** [comment]
> 就是点那个预览下面的垃圾桶的时候

目前是没有加，因为预览的删除操作是直接删除缓存里的图片，所以没考虑在删除那里需要跟接口有交互

**Comment by Kolentoo** [comment]
请问那怎么删啊，监听 fileList？好像不行吧

**Comment by eJayYoung** [comment]
那这样吧，我加个删除时的监听回调，会把fileList返回出来，晚上改

**Comment by Kolentoo** [comment]
哈哈哈这么给力，谢谢啊

**Comment by eJayYoung** [comment]
fixed, see on [v1.0.4](https://github.com/eJayYoung/vux-uploader-component/releases/tag/v1.0.4)
