### ISSUE TITLE
Wrong Content-Type and empty blob.type

### ISSUE THREAD

**Issue by stalcer** [eJayYoung/vux-uploader-component#10]
Greetings!

Last version (v1.0.22) replaced canvas.toBlob second parameter to file.type

Before that fix posted data was something like this (see wrong Content-Type):
------WebKitFormBoundaryBcBUpvEfzANNrA8m
Content-Disposition: form-data; name="image"; filename="twitter.svg"
Content-Type: image/jpeg

But now I see `application/octet-stream` content type instead of `image/svg+xml` (or any other matching type of image)
------WebKitFormBoundaryBcBUpvEfzANNrA8m
Content-Disposition: form-data; name="image"; filename="twitter.svg"
Content-Type: application/octet-stream

Blob receives empty `type` parameter.

Can you fix that?

**Comment by eJayYoung** [comment]
> Greetings!
> 
> Last version (v1.0.22) replaced canvas.toBlob second parameter to file.type
> 
> Before that fix posted data was something like this (see wrong Content-Type):
> ------WebKitFormBoundaryBcBUpvEfzANNrA8m
> Content-Disposition: form-data; name="image"; filename="twitter.svg"
> Content-Type: image/jpeg
> 
> But now I see `application/octet-stream` content type instead of `image/svg+xml` (or any other matching type of image)
> ------WebKitFormBoundaryBcBUpvEfzANNrA8m
> Content-Disposition: form-data; name="image"; filename="twitter.svg"
> Content-Type: application/octet-stream
> 
> Blob receives empty `type` parameter.
> 
> Can you fix that?

yeah, I'll figure it out

**Comment by eJayYoung** [comment]
I found the problem is cause by [export blob as new File option](https://github.com/eJayYoung/vux-uploader-component/commit/9e4321c2ea59e33022a90c56e5779a9d6f6f54cc)

see [MDN new File options](https://developer.mozilla.org/en-US/docs/Web/API/File/File#options)

> - type: A DOMString representing the MIME type of the content that will be put into the file. Defaults to a value of "".

so I'll fixed it soon by setting `File`'s `option.type` to `file.type`

**Comment by eJayYoung** [comment]
fixed, see it in [v1.0.23](https://github.com/eJayYoung/vux-uploader-component/releases/tag/v1.0.23)

**Comment by stalcer** [comment]
Thank you, it works!
