### ISSUE TITLE
English translations on alerts?

### ISSUE THREAD

**Issue by aleksandarspassov9** [eJayYoung/vux-uploader-component#11]
Is it possible to have translations to other languages or at least English to alert modals?

**Comment by eJayYoung** [comment]
Sorry for the late reply, currently does not support, I'll support in these two days, thanks for the proposal.

**Comment by eJayYoung** [comment]
It is supported in [v1.0.24](https://github.com/eJayYoung/vux-uploader-component/releases/tag/v1.0.24)

you can use prop `limitPrompt` to custom limit alert content

eg:
```html
<vux-uploader-component
  :limitPrompt="limit => `No more than ${limit} photos`"
></vux-uploader-component>
```
