### ISSUE TITLE
在图片预览界面滑动后的删除bug

### ISSUE THREAD

**Issue by Jay-G2017** [eJayYoung/vux-uploader-component#14]
现象: 上传两张图片, 点第一张图片的预览, 滑动到第二张, 点删除. 删掉的是第一张图片.
期待结果: 删掉的是当前预览页的图片, 也就是上面的第二张, 而不是第一张图片.

**Comment by eJayYoung** [comment]
> 现象: 上传两张图片, 点第一张图片的预览, 滑动到第二张, 点删除. 删掉的是第一张图片.
> 期待结果: 删掉的是当前预览页的图片, 也就是上面的第二张, 而不是第一张图片.

谢谢反馈，目前构建工具版本有点低需要升级，最近会完成升级并修复掉

**Comment by eJayYoung** [comment]
fixed, see [v1.0.25](https://github.com/eJayYoung/vux-uploader-component/releases/tag/v1.0.25) .
