### ISSUE TITLE
ios兼容性问题

### ISSUE THREAD

**Issue by caix-github** [eJayYoung/vux-uploader-component#16]
ios10点击上传组件没有响应，没有弹出文件弹窗

**Comment by eJayYoung** [comment]
你的容器是webview吗？
google上看了下大部分原因是UIWebview的问题

**Comment by eJayYoung** [comment]
https://www.cnblogs.com/yzeng/p/6639406.html

你可以看下去掉capture属性是否有效

**Comment by caix-github** [comment]
哦哦，你好，问题已经解决了，是ios日期格式没处理好的问题，谢谢



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年2月22日(星期二) 下午2:40
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [eJayYoung/vux-uploader-component] ios兼容性问题 (Issue #16)





 
https://www.cnblogs.com/yzeng/p/6639406.html
 
你可以看下去掉capture属性是否有效
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by eJayYoung** [comment]
> 
好的
