### ISSUE TITLE
请问 onChange(fileList)我想要获取文件的这个参数改掉了吗

### ISSUE THREAD

**Issue by Kolentoo** [eJayYoung/vux-uploader-component#2]
之前不是获取当前的文件咯，
现在改成 fileList了？

**Comment by Kolentoo** [comment]
因为我需要把文件转换成二进制的。

**Comment by eJayYoung** [comment]
> 因为我需要把文件转换成二进制的。

嗯，是的，因为删除的时候我返回的是vue组件自己拼装的FileList，所以这次在change的时候也统一返回这个数据，而且我在自动上传那里给数据做过二进制转换的，不过你可能不想要自动上传，这时候就需要获取真实的FileList对象吧？
我改一下吧

**Comment by Kolentoo** [comment]
谢谢啦




------------------ 原始邮件 ------------------
发件人: "eJay"<notifications@github.com>;
发送时间: 2019年5月5日(星期天) 下午4:04
收件人: "eJayYoung/vux-uploader-component"<vux-uploader-component@noreply.github.com>;
抄送: "To'めく風は跡が"<515835543@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [eJayYoung/vux-uploader-component] 请问 onChange(fileList)我想要获取文件的这个参数改掉了吗 (#2)



 
因为我需要把文件转换成二进制的。
  
嗯，是的，因为删除的时候我返回的是vue组件自己拼装的FileList，所以这次在change的时候也统一返回这个数据，而且我在自动上传那里给数据做过二进制转换的，不过你可能不想要自动上传，这时候就需要获取真实的FileList对象吧？
 我改一下吧

**Comment by eJayYoung** [comment]
fix, see on [v1.0.5](https://github.com/eJayYoung/vux-uploader-component/tree/v1.0.5)
想要获取组件data里的FileList可以通过v-model来获取

**Comment by eJayYoung** [comment]
> fix, see on [v1.0.5](https://github.com/eJayYoung/vux-uploader-component/tree/v1.0.5)
> 想要获取组件data里的FileList可以通过v-model来获取

又更新了一版，onDelete时不返回fileList了，想获取组件的fileList统一从v-model中获取，然后file的二进制也赋值到组件data的fileList中了，可以获取用来自己上传
