### ISSUE TITLE
canvas图片处理bug

### ISSUE THREAD

**Issue by yzc1023** [eJayYoung/vux-uploader-component#5]
直接访问demo地址
问题：
1.图片被纵向拉伸，测试的图片分辨率89*93
2.png图片透明处变黑
![image](https://user-images.githubusercontent.com/23627633/69416757-44255c80-0d52-11ea-915f-16b8d2d05a0d.png)

**Comment by eJayYoung** [comment]
收到，谢谢反馈，正在快速修复一版

**Comment by eJayYoung** [comment]
@yzc1023 fixed, [see v1.0.16](https://github.com/eJayYoung/vux-uploader-component/releases/tag/v1.0.16)
