### ISSUE TITLE
params header and withCredentials

### ISSUE THREAD

**Issue by djkdeveloper** [eJayYoung/vux-uploader-component#6]
大佬 组件能否支持设置 header参数和withCredentials

**Comment by eJayYoung** [comment]
> 大佬 组件能否支持设置 header参数和withCredentials

可以的，这两天我找时间改

**Comment by eJayYoung** [comment]
done, [see v1.0.17](https://github.com/eJayYoung/vux-uploader-component/releases/tag/v1.0.17)

**Comment by djkdeveloper** [comment]
谢谢大佬
