### ISSUE TITLE
iphone手机 iOS13系统 选择正方形拍摄的照片上传，选择图像大小以后，再上传，照片会旋转

### ISSUE THREAD

**Issue by Saikikoko** [eJayYoung/vux-uploader-component#8]

**Comment by Saikikoko** [comment]
iphonex上 只要是正方形的照片，上传后都会旋转，iPhone7像标题描述的一样操作，会旋转

**Comment by eJayYoung** [comment]
> iphonex上 只要是正方形的照片，上传后都会旋转，iPhone7像标题描述的一样操作，会旋转

确实，我已经在ios13上验证过了，也有其他人碰到了[类似的问题](https://juejin.im/post/5ec26d3c6fb9a043681f83c2)
我抽空会修复的，不过需要想一下如何检测浏览器会针对图片的EXIF信息自动旋转

**Comment by eJayYoung** [comment]
fixed, see [v1.0.18](https://github.com/eJayYoung/vux-uploader-component/releases/tag/v1.0.18)

**Comment by Saikikoko** [comment]
这个思路很不错，但是如果照片是旋转了180度的情况，这样判断就有问题

**Comment by eJayYoung** [comment]
> 这个思路很不错，但是如果照片是旋转了180度的情况，这样判断就有问题

浏览器只会根据图片拍摄的EXIF中的orientation，去判断如何自动旋转图片，而图片的orientation总共有8个值，不同的值需要旋转的角度都是不同的，在[我之前的笔记](https://juejin.im/post/5bd705abf265da0a8d36dbdc#heading-9)中有提到过
我拿来做测试判断的那个base64图片的orientation固定就是6，所以只需要这样判断，就没什么问题🤔

**Comment by Saikikoko** [comment]
明白了
