### ISSUE TITLE
PNG Images turn alpha channel to black background

### ISSUE THREAD

**Issue by DanielApodaca** [eJayYoung/vux-uploader-component#9]
Hi, i really like this component but when i try to upload png images with a transparent background they change the alpha channel to black, is there a way to keep the transparency? Im using `"vux-uploader-component": "^1.0.21"`
![](https://i.imgur.com/uuTnrM3.png)

**Comment by eJayYoung** [comment]
> Hi, i really like this component but when i try to upload png images with a transparent background they change the alpha channel to black, is there a way to keep the transparency? Im using `"vux-uploader-component": "^1.0.21"`
> ![](https://camo.githubusercontent.com/30744bc33cf364893b4e143719b98c2d359ff201/68747470733a2f2f692e696d6775722e636f6d2f7575546e724d332e706e67)

cause I wrote `canvas.toBlob()` the second parameter fixed as 'image/jpeg' ，[see this line](https://github.com/eJayYoung/vux-uploader-component/blob/master/src/utils.js#L191)
sorry for this mistake，I'll fixed it soon，glad you like it!

**Comment by eJayYoung** [comment]
fixed in [v1.0.22](https://github.com/eJayYoung/vux-uploader-component/releases/tag/v1.0.22)，tks for your feedback
